# Generated by Django 6.0.7 on 2026-10-06 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipos de Exame')),
            ],
        ),
        migrations.CreateModel(
            name='ExameEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('exame_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especificacoes', to='hospital.exame')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(help_text='Ex: Santos, Guarujá, São Vicente...', max_length=100)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('exames_disponiveis', models.ManyToManyField(to='hospital.exameespecifico')),
                ('planos_aceitos', models.ManyToManyField(to='hospital.planosaude')),
            ],
        ),
        migrations.AddField(
            model_name='exame',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exames', to='hospital.tipoexame'),
        ),
    ]
