# Generated by Django 6.0.7 on 2026-09-01 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('exame_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Especificacoes', to='hospital.exame')),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='exames_disponiveis',
            field=models.ManyToManyField(to='hospital.exameespecifico'),
        ),
    ]
