# Generated by Django 6.0.7 on 2026-09-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_exameespecifico_alter_hospital_exames_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='cidade',
            field=models.CharField(default='Santos', help_text='Ex: Santos, Guarujá, São Vicente...', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
